version: '3'
services:
  api:
    build: api/
    volumes:
      - ./gcp:/gcp
    ports:
      - "8080:8080"
    env_file: api/.env.compose
    networks:
      - app
  gateway:
    build: gateway/
    volumes:
      - ./gateway/app:/config
    ports:
      - "8000:8000"
    env_file: gateway/.env.compose
    networks:
      - app
  mail:
    build: mail/
    ports:
      - "8090:8090"
    env_file: mail/.env.compose
    networks:
      - app
  dashboard:
    build:
      context: dashboard/
      dockerfile: Dockerfile.dev
    ports:
      - "4200:80"
    networks:
      - app
networks:
  app:
    driver: bridge
