apiVersion: v1
kind: Service
metadata:
  name: csgames-api-prod-backend
spec:
  selector:
    app: csgames-api-prod
  ports:
  - name: csgames-api-prod-backend
    targetPort: 8080
    port: 8080
  - name: csgames-api-ws-prod-backend
    targetPort: 8081
    port: 8081
  type: NodePort