name: Staging CI

on:
  push:
    branches:
      - master

jobs:
  gateway:
    name: Gateway
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      working-directory: gateway
      run: docker build -t docker.pkg.github.com/csgames/event-platform/gateway:latest .
    - name: Login to Github Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u csgames --password-stdin
    - name: Pushing the Docker image
      run: docker push docker.pkg.github.com/csgames/event-platform/gateway:latest
  
  api:
    name: Api
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      working-directory: api
      run: docker build -t docker.pkg.github.com/csgames/event-platform/api:latest .
    - name: Login to Github Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u csgames --password-stdin
    - name: Pushing the Docker image
      run: docker push docker.pkg.github.com/csgames/event-platform/api:latest
  
  mail:
    name: Mail service
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      working-directory: mail
      run: docker build -t docker.pkg.github.com/csgames/event-platform/mail-service:latest .
    - name: Login to Github Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u csgames --password-stdin
    - name: Pushing the Docker image
      run: docker push docker.pkg.github.com/csgames/event-platform/mail-service:latest

  aws:
    name: Deploy on AWS
    needs: [gateway, api, mail]
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ./deployment/aws/staging/task-definition.json
        service: EventPlatform-Staging
        cluster: EventPlatform
